# Generated by Django 5.1.2 on 2024-11-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_view', 'Can view a post'), ('can_create', 'Can create a post'), ('can_edit', 'Can edit a post'), ('can_delete', 'Can delete a post')]},
        ),
    ]
